### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by jmcculloch4** [christianbaun/task-distributor#1]
The link to your PDF is broken.  I'm interested in using POVRAY as a visual demo to display application performance improvement of multi-node execution versus single node and motivate engineers to use our x86 cluster for their own work.

**Comment by jmcculloch4** [comment]
oops, just found a working link to the PDF in the documentation/literature directory.  The link on the main page is broken.

**Comment by christianbaun** [comment]
Thanks for the notification. I fixed the link.
